// packages/components/frameworks/react/src/App.js
import React, { useRef, useState } from 'react';
import './App.scss';
import { Popover } from '@elvia/elvis-popover/react';
import { Checkbox } from '@elvia/elvis-checkbox/react';
import { Tabs } from '@elvia/elvis-tabs/react';
import { ProgressLinear } from '@elvia/elvis-progress-linear/react';
import { Dropdown } from '@elvia/elvis-dropdown/react';

function App() {
  const [trackedState, setTrackedState] = useState(true);
  const [selectedState, setSelectedState] = useState(0);
  const ref = useRef();
  const items = [
    { label: 'Statistikk' },
    { label: 'Siste kall' },
    { label: 'HAN-port' },
    { label: 'Feilkategorisering' },
  ];

  function update() {
    setTrackedState(!trackedState);
  }

  const [progressValue, setProgressValue] = useState(0);

  function increaseProgress() {
    setProgressValue((prevProgValue) => prevProgValue + 10);
  }
  function decreaseProgress() {
    setProgressValue((prevProgValue) => prevProgValue - 10);
  }
  function resetProgress() {
    setProgressValue(0);
  }

  const options = [
    {
      value: 'norge',
      label: 'Norge',
    },
    {
      value: 'sverige',
      label: 'Sverige',
    },
    {
      value: 'danmark',
      label: 'Danmark',
    },
    {
      value: 'finland',
      label: 'Finland',
    },
    {
      value: 'island',
      label: 'Island',
    },
    {
      value: 'island1',
      label: 'Island',
    },
    {
      value: 'islan2d',
      label: 'Island',
    },
    {
      value: 'island3',
      label: 'Island',
    },
    {
      value: 'islan4d',
      label: 'Island',
    },
    {
      value: 'islan5d',
      label: 'Island',
    },
  ];

  return (
    <div className="App">
      <h1>React preview</h1>

      <h2>Dropdown</h2>
      <div>
        <Dropdown options={options} ></Dropdown>
      </div>

      <h2>Tabs</h2>
      <div style={{ marginTop: '16px' }}>
        <Tabs items={items} value={selectedState} valueOnChange={setSelectedState}></Tabs>
        <div>{selectedState.toString()}</div>
      </div>

      <hr style={{ margin: '40px 0' }} />

      <h2>Checkbox</h2>
      <div style={{ marginTop: '16px' }}>
        <Checkbox
          ref={ref}
          checked={trackedState}
          label="Normal checkbox"
          name="Nametest"
          id="CheckboxTestID"
          size="normal"
          changeHandler={setTrackedState}
        ></Checkbox>
        <Checkbox label="Small checkbox" name="Nametest" id="CheckboxTestID" size="small"></Checkbox>
      </div>

      <hr style={{ margin: '40px 0' }} />

      <h2>Popover</h2>
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end' }}>
        <span style={{ marginTop: '16px' }}>
          <Popover
            title="BankID"
            content="Alle privatkunder må bruke BankID første gang. Alle privatkunder må bruke BankID første gang. Alle privatkunder må bruke BankID første gang."
            trigger={<button>Right top</button>}
            posX="right"
          ></Popover>
        </span>
        <div style={{ marginTop: '16px' }}>
          <Popover
            content="Alle privatkunder må bruke BankID."
            trigger={<button>Left top</button>}
            posX="left"
            noTitle="true"
          ></Popover>
        </div>
        <div style={{ marginTop: '16px' }}>
          <Popover
            title="BankID"
            content="Alle privatkunder må bruke BankID første gang de logger inn på Min side."
            trigger={<button>Center top</button>}
            hasCloseBtn={false}
          ></Popover>
        </div>
      </div>
      <div style={{ marginTop: '16px' }}>
        <Popover
          content="Alle privatkunder må bruke BankID første gang."
          trigger={<button>Center bottom</button>}
          hasCloseBtn={false}
          posY="bottom"
        ></Popover>
      </div>
      <div style={{ marginTop: '16px' }}>
        <Popover
          title="BankID"
          content="Alle privatkunder må bruke BankID første gang."
          trigger={<button>Right bottom</button>}
          posY="bottom"
          posX="right"
        ></Popover>
      </div>
      <div style={{ marginTop: '16px' }}>
        <Popover
          content={
            <div
              style={{
                boxSizing: 'border-box',
                padding: '50px',
                width: '100%',
                border: '2px dashed lightgray',
              }}
            >
              Custom content custom content custom content custom content
            </div>
          }
          trigger={<button>Left bottom</button>}
          posY="bottom"
          posX="left"
        ></Popover>
      </div>

      <h2>Progressbar</h2>

      <ProgressLinear value={progressValue}></ProgressLinear>

      <div style={{ width: '100%', display: 'flex', justifyContent: 'space-around' }}>
        <button onClick={increaseProgress}>Increase</button>
        <button onClick={decreaseProgress}>Decrease</button>
        <button onClick={resetProgress}>reset</button>
      </div>
      <div>{progressValue}</div>

      <h2>Progressbar indeterminate</h2>

      <div>
        <ProgressLinear isIndeterminate></ProgressLinear>
      </div>
      <h2>Progressbar Error</h2>

      <div>
        <ProgressLinear isError></ProgressLinear>
      </div>
    </div>
  );
}

export default App;

// packages/components/frameworks/angular/src/app/app.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  @ViewChild('checkbox1', { static: true }) checkbox: any;
  checkBoxVal = true;
  checkBoxVal2 = true;
  progressValue = 0;

  items = [
    { label: 'Epler' },
    { label: 'Appelsin' },
    { label: 'Bananer' },
    { label: 'Druer' },
    { label: 'Kiwi', disabled: true },
  ];
  value = 0;

  dropdownOptions = [
    {
      value: 'norge',
      label: 'Norge',
    },
    {
      value: 'sverige',
      label: 'Sverige',
    },
    {
      value: 'danmark',
      label: 'Danmark',
    },
  ];

  nativeJSApproach(): void {
    // Non-angular approach, not necessary when using angular:
    this.checkbox.nativeElement.addEventListener('checkedOnChange', (event: any) => {
      this.checkBoxVal2 = event.detail.checked;
    });
    this.checkbox.nativeElement.setProps({ checked: this.checkBoxVal2 });
    // If you need to get data at any other time: this.checkbox.nativeElement.getProps();
  }

  ngOnInit(): void {
    this.nativeJSApproach();
  }
}

<div class="App">
  <h1>Angular preview</h1>


  <h2>Dropdown</h2>
  <div style="margin-top: 16px">
    <div style="margin-bottom: 16px;padding: 12px">
      Selected options: {{ selectedOptions | json }}
    </div>
    <elvia-dropdown
      [options]='dropdownOptions'
      (valueOnChange)="selectedOptions = $event.detail.value"
    ></elvia-dropdown>
  </div>

  <h2>Tabs</h2>
  <div style="margin-top: 16px; background: #262626">
    <elvia-tabs
      [items]="['Epler', 'Appelsin', 'Bananer', 'Druer', 'Kiwi']"
      [value]="1"
      [isInverted]="true"
      (valueOnChange)="value = $event.detail.value"
    ></elvia-tabs>
  </div>
  <elvia-tabs
    [items]="['Epler', 'Appelsin', 'Bananer', 'Druer', 'Kiwi']"
    [value]="1"
    (valueOnChange)="value = $event.detail.value"
  ></elvia-tabs>
  {{ value }}

  <hr style="margin: 40px 0" />
  <elvia-testing
    [value]="counterValue"
    (valueOnChange)="counterValue = $event.detail.value"
  ></elvia-testing>
  {{ counterValue }}
  <button (click)="counterValue = counterValue + 1">++</button>

  <hr style="margin: 40px 0" />

  <h2>Popover</h2>
  <div style="display: flex; flex-direction: column; align-items: flex-end">
    <div style="margin-top: 16px">
      <elvia-popover
        header="BankID"
        posX="right"
        width="200"
      >
        <button
          slot="trigger"
          class="e-btn"
        >Right top</button>
        <div slot="content">
          Alle privatkunder må bruke BankID første gang. Alle privatkunder må bruke BankID første gang.
        </div>
      </elvia-popover>
    </div>
    <div style="margin-top: 16px">
      <elvia-popover
        header="BankID"
        content="Alle privatkunder må bruke BankID første gang. Alle privatkunder må bruke BankID første gang. Alle
        privatkunder må bruke BankID første gang."
        posX="left"
        hasCloseBtn="false"
      >
        <button
          slot="trigger"
          class="e-btn"
        >Left top</button>
      </elvia-popover>
    </div>
    <div style="margin-top: 16px">
      <elvia-popover
        header="BankID"
        content="Alle privatkunder må bruke BankID."
      >
        <button
          slot="trigger"
          class="e-btn"
        >Center top</button>
      </elvia-popover>
    </div>
  </div>
  <div style="margin-top: 16px">
    <elvia-popover
      header="BankID"
      content="Alle privatkunder må bruke BankID."
      posY="bottom"
    >
      <button
        slot="trigger"
        class="e-btn"
      >Center bottom</button>
    </elvia-popover>
  </div>
  <div style="margin-top: 16px">
    <elvia-popover
      header="BankID"
      content="Alle privatkunder må bruke BankID første gang de skal logge inn på Min side."
      posY="bottom"
      posX="right"
    >
      <button
        slot="trigger"
        class="e-btn"
      >Right bottom</button>
    </elvia-popover>
  </div>
  <div style="margin-top: 16px">
    <elvia-popover
      header="BankID"
      content="Alle privatkunder må bruke BankID første gang de skal logge inn på Min side."
      posY="bottom"
      posX="left"
    >
      <button
        slot="trigger"
        class="e-btn"
      >Left bottom</button>
    </elvia-popover>
  </div>

  <hr style="margin: 40px 0" />

  <h2>Progressbar</h2>
  <div style="margin-bottom: 32px; display: flex">
    <elvia-progress-linear
      [isIndeterminate]="indeterminate"
      [value]="progressValue"
      [isError]="progressError"
    ></elvia-progress-linear>
    <div style="display: flex; width: 100%; justify-content: space-between">
      <button (click)="progressValue = progressValue + 10">Increase Progress</button>
      <button (click)="progressValue = progressValue - 10">Decrease Progress</button>
      <button (click)="progressValue = 0">Reset Progress</button>
      <button (click)="indeterminate = !indeterminate">Toggle indeterminate</button>
      <button (click)="progressError = !progressError">Toggle error</button>
    </div>
  </div>
</div>
