// packages/react-test/src/Components.tsx
import { Accordion } from '@elvia/elvis-accordion/react';
import { Autocomplete } from '@elvia/elvis-autocomplete/react';
import { Badge } from '@elvia/elvis-badge/react';
import { Box } from '@elvia/elvis-box/react';
import { Card } from '@elvia/elvis-card/react';
import { Carousel } from '@elvia/elvis-carousel/react';
import { Chip } from '@elvia/elvis-chip/react';
import { ContextMenu } from '@elvia/elvis-context-menu/react';
import { DatepickerRange } from '@elvia/elvis-datepicker-range/react';
import { Datepicker } from '@elvia/elvis-datepicker/react';
import { Divider } from '@elvia/elvis-divider/react';
import { Dropdown } from '@elvia/elvis-dropdown/react';
import { Icon } from '@elvia/elvis-icon/react';
import { Modal } from '@elvia/elvis-modal/react';
import { Pagination } from '@elvia/elvis-pagination/react';
import { Popover } from '@elvia/elvis-popover/react';
import { ProgressLinear } from '@elvia/elvis-progress-linear/react';
import { RadioFilter } from '@elvia/elvis-radio-filter/react';
import { SegmentedControl } from '@elvia/elvis-segmented-control/react';
import { Slider } from '@elvia/elvis-slider/react';
import { Spotlight } from '@elvia/elvis-spotlight/react';
import { Stepper } from '@elvia/elvis-stepper/react';
import { Tabs } from '@elvia/elvis-tabs/react';
import { Timepicker } from '@elvia/elvis-timepicker/react';
import { openElviaToast } from '@elvia/elvis-toast';
import { Tooltip } from '@elvia/elvis-tooltip/react';
import { useState } from 'react';

export const Components: React.FC = () => {
  const logValue = (component: string, value: string | number) => {
    console.log(component, ': ', value);
  };
  const updateSpotlight = () => {
    const { innerWidth, innerHeight } = window;
    const newSize = 30 + Math.random() * 100;
    const newPos = {
      vertical: Math.random() * (innerHeight - 2 * newSize) + newSize,
      horizontal: Math.random() * (innerWidth - 2 * newSize) + newSize,
    };
    setSpotlightState({ pos: newPos, size: newSize });
  };

  // Accordion
  const [isOpenContent, setIsOpenContent] = useState(false);

  //Autocomplete
  const autocompleteItems = [
    { value: 'Appelsin', label: 'Appelsin' },
    { value: 'Banan', label: 'Banan' },
    { value: 'Eple', label: 'Eple' },
    { value: 'Jordbær', label: 'Jordbær' },
    { value: 'Pære', label: 'Pære' },
    { value: 'Vannmelon', label: 'Vannmelon' },
    { value: 'Druer', label: 'Druer' },
  ];

  // Breadcrumb
  const breadcrumbsNoUrl = [
    {
      text: 'Elvia.no',
    },
    {
      text: 'Nettleie',
    },
  ];

  // Chip
  const [chipSelected, setChipSelected] = useState(false);

  // Context menu
  const [isContextMenuShowing, setIsContextMenuShowing] = useState(false);

  // Datepicker
  const dateFromToday = (diff: number): Date => {
    const d = new Date();
    d.setDate(d.getDate() + diff);
    return d;
  };
  let minDate = dateFromToday(-5);
  let maxDate = dateFromToday(-1);
  const [datepickerValue, setDatepickerValue] = useState<Date | null>(null);

  // Dropdown
  const defaultDropdownOptions = 'norge';
  const dropdownOptions = [
    { value: 'norge', label: 'Norge' },
    { value: 'sverige', label: 'Sverige' },
    { value: 'danmark', label: 'Danmark' },
    {
      value: 'england',
      label: 'England',
      children: [
        { value: 'london', label: 'London' },
        { value: 'manchester', label: 'Manchester' },
        { value: 'birmingham', label: 'Birmingham' },
      ],
    },
    { value: 'russland', label: 'Russland' },
    { value: 'polen', label: 'Polen' },
    { value: 'romania', label: 'Romania' },
    { value: 'frankrike', label: 'Frankrike' },
    { value: 'spania', label: 'Spania' },
    { value: 'portugal', label: 'Portugal' },
    { value: 'italia', label: 'Italia' },
    { value: 'finland', label: 'Finland' },
    { value: 'østerriket', label: 'Østerriket' },
  ];

  const [isLoadingMoreItems, setIsLoadingMoreItems] = useState(false);
  const onLoadMoreItems = () => {
    setIsLoadingMoreItems(true);
    setTimeout(() => {
      setIsLoadingMoreItems(false);
    }, 2000);
  };

  // Modal
  const [isModalShowing, setIsModalShowingState] = useState(false);

  // Popover
  const [isPopoverShowing, setIsPopoverShowingState] = useState(false);

  // Progressbar
  const [progressValue, setProgressValue] = useState(0);
  function increaseProgress() {
    setProgressValue((prevProgValue) => prevProgValue + 10);
  }
  function decreaseProgress() {
    setProgressValue((prevProgValue) => prevProgValue - 10);
  }

  // Radio filter
  const [selectedRadioFilter, setSelectedRadioFilter] = useState('read');
  const radioFilterOptions = [
    { label: 'All', value: 'all' },
    { label: 'Read', value: 'read' },
    { label: 'Unread', value: 'unread' },
  ];

  // Spotlight
  const [spotlightIsShowing, setSpotlightIsShowing] = useState(false);
  const [spotlightState, setSpotlightState] = useState({
    pos: { vertical: window.innerWidth / 2 - 200, horizontal: window.innerHeight / 2 + 200 },
    size: 100,
  });

  // Tabs
  const tabsItems = ['Statistikk', 'Siste kall', 'HAN-port', 'Feilkategorisering'];
  const [isChipLoading, setIsChipLoading] = useState(false);

  // Toast
  const showToast = () => {
    openElviaToast({
      title: 'Test title',
      body: 'This is an information toast',
      status: 'informative',
      closable: true,
      duration: 2000000,
    });
  };

  return (
    <>
      {/* CURRENTLY TESTING */}
      <div className="example-wrapper">
        {/* Test the component here (delete what was here previously). When done add it to the list alphabetically */}
        <h3>Test your component here</h3>
        {/* Normal version */}
        <div>
          <Accordion
            isOpen={true}
            isFullWidth
            openLabel={'Show'}
            closeLabel={'Hide'}
            content={
              <Accordion
                isOpen={true}
                isFullWidth
                openLabel={'Show'}
                closeLabel={'Hide'}
                content={<div>Content</div>}
              />
            }
          />
        </div>
      </div>
      {/* ACCORDION */}
      <div className="example-wrapper">
        <h3>Accordion</h3>
        <button onClick={() => setIsOpenContent((prevIsOpen) => !prevIsOpen)}>Trigger animation</button>
        <Accordion
          isOpen={isOpenContent}
          type={'overflow'}
          openLabel={'Show'}
          closeLabel={'Hide'}
          overflowHeight={100}
          labelPosition={'center'}
          size={'medium'}
          content={
            'It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. '
          }
        ></Accordion>
      </div>

      {/* AUTOCOMPLETE */}
      <div className="example-wrapper">
        <h3>Autocomplete</h3>
        <Autocomplete
          items={autocompleteItems}
          label="Skriv inn en frukt"
          placeholder="banan..."
          valueOnChange={(value) => {
            console.info('valueOnChange:', value);
          }}
        />
      </div>

      {/* BADGE */}
      <div className="example-wrapper">
        <h3>Badge</h3>

        <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          <Badge
            content={
              <button
                className="e-thumbnail"
                aria-label="Thumbnail button that opens the image in a larger view"
              >
                <img src="https://picsum.photos/200" alt="Thumbnail example image" />
              </button>
            }
          />

          <Badge
            badgeColor={'red'}
            count={8}
            content={
              <button
                className="e-thumbnail"
                aria-label="Thumbnail button that opens the image in a larger view"
              >
                <img src="https://picsum.photos/200" alt="Thumbnail example image" />
              </button>
            }
          />

          <Badge
            badgeColor={'neutral'}
            count={101}
            content={
              <button
                className="e-thumbnail"
                aria-label="Thumbnail button that opens the image in a larger view"
              >
                <img src="https://picsum.photos/200" alt="Thumbnail example image" />
              </button>
            }
          />

          <Badge
            badgeColor={'neutral'}
            content={
              <button
                className="e-thumbnail"
                aria-label="Thumbnail button that opens the image in a larger view"
              >
                <img src="https://picsum.photos/200" alt="Thumbnail example image" />
              </button>
            }
          />
        </div>
      </div>
      {/* BOX */}
      <div className="example-wrapper">
        <h3>Box</h3>
        <Box
          isColored={true}
          heading={<h1>Title for the box component</h1>}
          content={<div>Heisann dette er en box component sendt med som node i react</div>}
        ></Box>
      </div>

      {/* CARD */}
      <div className="example-wrapper">
        <h3>Card</h3>
        <Card
          heading={'Title1'}
          borderColor={'red'}
          icon={<i className="e-icon e-icon--search-bold e-icon--md" aria-hidden="true"></i>}
          iconHover={<i className="e-icon e-icon--search-bold-color e-icon--md" aria-hidden="true"></i>}
          cornerIcon={<Icon name="unlock" size="xs" />}
        ></Card>
      </div>
      {/* CAROUSEL */}
      <div className="example-wrapper">
        <h3>Carousel</h3>
        <Carousel
          type="linear"
          hasConfirmationCheckmark={true}
          items={[
            { heading: <h3 className="e-title-sm">HAN-port</h3>, item: <div>Hallo</div> },
            { heading: <h3 className="e-title-sm">AMS-meter</h3>, item: 'Hei' },
            {
              heading: <h3 className="e-title-sm">About login</h3>,
              item: <p>Halla</p>,
            },
          ]}
          onFinish={() => console.log('Hide')}
        />
      </div>
      {/* CHIP */}
      <div className="example-wrapper">
        <h3>Chip</h3>
        <Chip type={'choice'} value={2022} isSelected={true}></Chip>
        <Chip type={'choice'} value={'Disabled'} isDisabled></Chip>

        <Chip
          type="legend"
          isSelectedOnChange={() => {
            setChipSelected(!chipSelected);
            setIsChipLoading(!isChipLoading);
            setTimeout(() => {
              setIsChipLoading(false);
            }, 2000);
          }}
          isSelected={chipSelected}
          isLoading={isChipLoading}
          value="Selectable"
          color="red"
        ></Chip>
      </div>
      {/* CONTEXT MENU */}
      <div className="example-wrapper">
        <h3>Context menu</h3>
        <ContextMenu
          onOpen={() => setIsContextMenuShowing(true)}
          onClose={() => setIsContextMenuShowing(false)}
          trigger={
            <button
              className={`e-btn e-btn--icon ${isContextMenuShowing ? 'e-btn---selected' : ''}`}
              aria-label="More menu"
            >
              <span className="e-btn__icon">
                <i className="e-icon e-icon--more_menu e-icon--inverted" aria-hidden="true"></i>
                <i className="e-icon e-icon--more_menu" aria-hidden="true"></i>
              </span>
            </button>
          }
          content={
            <>
              <div className="ewc-context-menu__list-group">
                <button>
                  <span>Be om tilgang</span>
                </button>
                <button>
                  <span>Legg til bruker</span>
                </button>
              </div>
              <div className="ewc-context-menu__list-group">
                <a>
                  <span>Endre passord</span>
                </a>
              </div>
            </>
          }
        ></ContextMenu>
      </div>
      {/* DATEPICKER */}
      <div className="example-wrapper">
        <h3>Datepicker</h3>
        <Datepicker valueOnChange={(value) => console.log(value)} hasSelectDateOnOpen={false}></Datepicker>
      </div>
      {/* DATE RANGE PICKER */}
      <div className="example-wrapper">
        <h3>Date range picker</h3>
        <DatepickerRange valueOnChange={(event) => console.log(event)}></DatepickerRange>
      </div>
      {/* DIVIDER */}
      <div className="example-wrapper">
        <h3>Divider</h3>
        <Divider />
      </div>
      {/* DROPDOWN */}
      <div className="example-wrapper">
        <h3>Dropdown</h3>
        <Dropdown
          value={defaultDropdownOptions}
          placeholder="Select country"
          label="New dropdown"
          isSearchable
          items={dropdownOptions}
          isMulti
          isLoadingMoreItems={isLoadingMoreItems}
          onLoadMoreItems={onLoadMoreItems}
        ></Dropdown>
      </div>
      {/* ICON */}
      <div className="example-wrapper">
        <h3>Icon</h3>
        <Icon name="arrowLeftBold"></Icon>
        <Icon name="arrowRightBold"></Icon>
      </div>
      {/* MODAL */}
      <div className="example-wrapper">
        <h3>Modal</h3>
        <button className="e-btn" onClick={() => setIsModalShowingState(true)}>
          Show modal
        </button>
        <Modal
          isShowing={isModalShowing}
          hasCloseButton
          onClose={() => setIsModalShowingState(false)}
          heading="Title of content"
          content={<div>Body text comes here and can go over several lines.</div>}
          primaryButton={<button className="e-btn e-btn--primary">Primary</button>}
          secondaryButton={<button className="e-btn e-btn--secondary">Secondary</button>}
        ></Modal>
      </div>
      {/* PAGINATION */}
      <div className="example-wrapper">
        <h3>Pagination</h3>
        <Pagination
          numberOfElements={100}
          lastNumberLimit={99}
          dropdownMenuPosition="top"
          labelOptions={{ displaying: 'Showing' }}
          alignment={'left'}
        ></Pagination>
      </div>
      {/* POPOVER */}
      <div className="example-wrapper">
        <h3>Popover</h3>
        <Popover
          heading="BankID"
          hasCloseButton
          content={<Tabs items={tabsItems} value={2}></Tabs>}
          trigger={<button className="e-btn">Show popover</button>}
          horizontalPosition="left"
          verticalPosition="top"
          isShowing={isPopoverShowing}
          onOpen={() => setIsPopoverShowingState(true)}
          onClose={() => setIsPopoverShowingState(false)}
        ></Popover>
      </div>
      {/* PROGRESS LINEAR */}
      <div className="example-wrapper">
        <h3>ProgressLinear</h3>
        <ProgressLinear value={progressValue}></ProgressLinear>
        <button className="e-btn e-mr-8" onClick={decreaseProgress}>
          Decrease
        </button>
        <button className="e-btn" onClick={increaseProgress}>
          Increase
        </button>
      </div>
      {/* RADIO FILTER */}
      <div className="example-wrapper">
        <h3>Radio filter</h3>
        <RadioFilter
          items={radioFilterOptions}
          ariaLabel={`${selectedRadioFilter} filtrering valgt`}
          valueOnChange={(selected) => {
            setSelectedRadioFilter(selected);
          }}
          value={selectedRadioFilter}
          name={'radioFilterTest'}
        ></RadioFilter>
      </div>
      {/* SEGMENTED CONTROL */}
      <div className="example-wrapper">
        <h3>Segmented Control</h3>
        <SegmentedControl
          items={[{ label: 'Different' }, { label: 'Length' }, { label: 'Woords' }]}
          size={'medium'}
          value={0}
          valueOnChange={(value) => console.log(value)}
        ></SegmentedControl>
        <div className="e-mt-8">
          <SegmentedControl
            type="icon"
            items={[
              {
                icon: '<i class="e-icon e-icon--access_control"></i>',
                iconSelected: '<i class="e-icon e-icon--access_control-color"></i>',
                ariaLabel: '',
              },
              {
                icon: '<i class="e-icon e-icon--list"></i>',
                iconSelected: '<i class="e-icon e-icon--list-color"></i>',
                ariaLabel: '',
              },
            ]}
            size={'large'}
            value={0}
            valueOnChange={(value) => console.log(value)}
          ></SegmentedControl>
        </div>
      </div>
      {/* SLIDER */}
      <div className="example-wrapper">
        <h3>Slider</h3>
        <h4>Simple</h4>
        <Slider />
        <h4>Range</h4>
        <Slider type={'range'} />
      </div>
      {/* SPOTLIGHT */}
      <div className="example-wrapper">
        <h3>Spotlight</h3>
        {spotlightIsShowing && (
          <Spotlight position={spotlightState.pos} radius={spotlightState.size}></Spotlight>
        )}
        <button
          onClick={() => setSpotlightIsShowing((prevVal) => !prevVal)}
          style={{ position: 'relative', zIndex: 999999 }}
          className="e-btn e-mr-8"
        >
          Show spotlight
        </button>
        <button onClick={updateSpotlight} style={{ position: 'relative', zIndex: 999999 }} className="e-btn">
          Update spotlight
        </button>
      </div>

      {/* STEPPER */}
      <div className="example-wrapper">
        <h3>Stepper</h3>
        <Stepper
          type={'horizontal'}
          steps={{
            1: { heading: 'Tittel 1', isCompleted: true },
            2: { heading: 'Tittel 2', isCompleted: true },
            3: { heading: 'Tittel 3' },
            4: { heading: 'Tittel 4', nextButtonText: 'Lagre' },
          }}
          content={[
            <div className="stepper-content-example">Trinn 1 innhold</div>,
            <div className="stepper-content-example">Trinn 2 innhold</div>,
            <div className="stepper-content-example">Trinn 3 innhold</div>,
            <div className="stepper-content-example">Trinn 4 innhold</div>,
          ]}
        />
      </div>

      {/* TABS */}
      <div className="example-wrapper">
        <h3>Tabs</h3>
        <Tabs items={tabsItems} value={2} valueOnChange={(event) => logValue('Tabs', event)}></Tabs>
      </div>

      {/* TIMEPICKER */}
      <div className="example-wrapper">
        <h3>Timepicker</h3>
        <Timepicker />
      </div>

      {/* TOAST */}
      <button className="e-btn" onClick={showToast}>
        Show toast
      </button>

      {/* TOOLTIP */}
      <Tooltip
        trigger={
          <button className="e-btn e-btn--icon e-btn--lg" aria-label="Vis tooltip">
            <span className="e-btn__icon">
              <i className="e-icon e-icon--star" aria-hidden="true"></i>
            </span>
          </button>
        }
        content={'Tooltip content'}
      />
    </>
  );
};

// packages/components/frameworks/vue-test/src/Components.vue
<template>
  <div class="components-examples">
    <div class="example-wrapper">
      <!--Test the component here (delete what was here previously). When done add it to the list alphabetically-->
      <h3>Test your component here</h3>
      <!--Normal version-->
      <div class="e-bg-white"></div>
      <!--Inverted version-->
      <div class="e-bg-grey"></div>
    </div>

    <!--Accordion-->
    <div class="example-wrapper">
      <h3>Accordion</h3>
      <button class="e-btn" @click="openAccordion = !openAccordion">toggle</button>
      {{ openAccordion }}
      <elvia-accordion
        openLabel="Show"
        closeLabel="Hide"
        size="medium"
        type="overflow"
        :isOpen="openAccordion"
        :overflowHeight="10"
      >
        <div slot="content">
          Webcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          componenWebcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          componenWebcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          componenWebcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          component
        </div>
      </elvia-accordion>
    </div>

    <!--Box-->
    <div class="example-wrapper">
      <h3>Box</h3>
      <elvia-box :hasBorder="true" :isColored="true">
        <div slot="title"><h1>Title for the box component</h1></div>
        <div slot="content">Webcomponentent content for the Box component</div>
      </elvia-box>
    </div>

    <!--Breadcrumb-->
    <div class="example-wrapper">
      <h3>Breadcrumb</h3>
      <elvia-breadcrumb :items="breadcrumbsTestNoUrl"></elvia-breadcrumb>
    </div>

    <!--Card-->
    <div class="example-wrapper">
      <h3>Card</h3>
      <elvia-card :header="'Header'" :description="'Hover me!'">
        <div slot="icon">91</div>
        <div slot="iconHover">92</div>
        <i slot="cornerIcon" class="e-icon e-icon--lock e-icon--xs" aria-hidden="true"></i>
      </elvia-card>
    </div>

    <!--Carousel-->
    <div class="example-wrapper">
      <h3>Carousel</h3>
      <elvia-carousel :hasAnimation="false" :value="carouselValue">
        <div slot="title-1">
          <h4 class="e-title-sm">HAN-port</h4>
        </div>
        <div slot="item-1">hello</div>
        <div slot="title-2">
          <h4 class="e-title-sm">AMS-meter</h4>
        </div>
        <div slot="item-2">halla</div>
        <div slot="title-3">
          <h4 class="e-title-sm">YOYOYO</h4>
        </div>
        <div slot="item-3">hei</div>
      </elvia-carousel>
      <button @click="carouselValue = incrementCarouselStep()" class="e-btn e-btn--sm">Increment step</button>
    </div>

    <!--Chip-->
    <div class="example-wrapper">
      <h3>Chip</h3>
      <div v-for="chip in deletableChipsList" :key="chip.value">
        <elvia-chip
          :type="'legend'"
          :value="chip.value"
          :color="chip.color"
          :ariaLabel="'Fjern filtrering for ' + chip.value"
          :isDisabled="chip.isDisabled"
          :isSelected="true"
          @is-selected-on-change="logValue('chip', $event.detail.value)"
        ></elvia-chip>
      </div>
    </div>

    <!--Datepicker-->
    <div class="example-wrapper">
      <h3>Datepicker</h3>
      <elvia-datepicker
        :isCompact="false"
        label="Fra dato"
        :disableDate="(day) => day.getDay() === 0 || day.getDay() === 6"
      ></elvia-datepicker>
    </div>

    <!--Date range picker-->
    <div class="example-wrapper">
      <h3>Date range picker</h3>
      <elvia-datepicker-range
        @value-on-change="logValue('range', $event.detail.value)"
      ></elvia-datepicker-range>
    </div>

    <!--Divider-->
    <div class="example-wrapper">
      <h3>Divider</h3>
      <elvia-divider></elvia-divider>
      <elvia-divider :isInverted="false" :type="'title'">
        <h2 slot="title">Title</h2>
      </elvia-divider>
    </div>

    <!--Dropdown-->
    <div class="example-wrapper">
      <h3>Dropdown</h3>
      <elvia-dropdown :value="dropdownDefaultOption" :items="dropdownOptions"></elvia-dropdown>
    </div>

    <!--Ikon-->
    <div class="example-wrapper">
      <h3>Icon</h3>
      <elvia-icon name="arrowLeftBold"></elvia-icon>
      <elvia-icon name="arrowRightBold"></elvia-icon>
    </div>

    <!--Modal-->
    <div class="example-wrapper">
      <h3>Modal</h3>
      <button class="e-btn" @click="isModalShowing = !isModalShowing">Hello</button>
      <elvia-modal
        :isShowing="isModalShowing"
        :heading="'Redigere bidragsytere'"
        :hasCloseButton="true"
        @on-close="isModalShowing = !isModalShowing"
      >
        <div slot="content">
          <div class="date-container">
            <elvia-datepicker :isCompact="true"></elvia-datepicker>
          </div>
        </div>
        <div slot="secondaryButton">
          <button class="e-btn e-btn--secondary e-btn--lg" @click="isModalShowing = false">Avbryt</button>
        </div>
        <div slot="primaryButton"><button class="e-btn e-btn--primary e-btn--lg">Lagre</button></div>
      </elvia-modal>
    </div>

    <!--Pagination-->
    <div class="example-wrapper">
      <h3>Pagination</h3>
      <elvia-pagination
        :numberOfElements="156"
        :value="defaultPaginationValue"
        :dropdownMenuPosition="'top'"
      ></elvia-pagination>
    </div>

    <!--Popover-->
    <div class="example-wrapper">
      <h3>Popover</h3>
      <elvia-popover heading="BankID" horizontalPosition="right">
        <div slot="trigger"><button class="e-btn">Right top</button></div>
        <div slot="content">
          Alle privatkunder må bruke BankID første gang. Alle privatkunder må bruke BankID første gang.
        </div>
      </elvia-popover>
    </div>

    <!--Progress linear-->
    <div class="example-wrapper">
      <h3>Progress linear</h3>
      <elvia-progress-linear :value="50" :isIndeterminate="false" :isError="false"></elvia-progress-linear>
    </div>

    <!--Radio filter-->
    <div class="example-wrapper">
      <h3>Radio Filter</h3>
      <elvia-radio-filter
        :items="[
          { label: 'All', value: 'all' },
          { label: 'Read', value: 'read' },
          { label: 'Unread', value: 'unread' },
        ]"
        :value="'read'"
        :name="'readRadioFilters'"
        :ariaLabel="'{value} filtrering valgt'"
      ></elvia-radio-filter>
    </div>

    <!--Spotlight-->
    <div class="example-wrapper">
      <h3>Spotlight</h3>
      <!-- <elvia-spotlight :position="{ horizontal: hPos, vertical: vPos }" :radius="radius"></elvia-spotlight> -->
      <button @click="moveSpotlight()" style="z-index: 2147483647; position: relative">Move spotlight</button>
    </div>

    <!--Tabs-->
    <div class="example-wrapper">
      <h3>Tabs</h3>
      <elvia-tabs
        :items="['Epler', 'Appelsin', 'Bananer', 'Druer', 'Kiwi']"
        :value="1"
        :isInverted="false"
      ></elvia-tabs>
    </div>

    <!--Timepicker-->
    <div class="example-wrapper">
      <h3>Timepicker</h3>
      <elvia-timepicker @value-on-change="onTimepickerChange($event.detail.value)" label="Vue timepicker" />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  setup() {
    // Accordion
    const openAccordion = ref(false);
    // Breadcrumb
    const breadcrumbsTest = [
      { href: 'https://elvia.no', text: 'Elvia.no' },
      { href: 'https://www.elvia.no/nettleie', text: 'Nettleie' },
      { href: 'https://www.elvia.no/nettleie/elvias-leveringsplikt', text: 'Elvias leveringsplikt' },
    ];

    const breadcrumbsTestNoUrl = [
      { text: 'Elvia.no' },
      { text: 'Nettleie' },
      { text: 'Elvias leveringsplikt' },
    ];

    const carouselValue = ref(0);

    // Chips
    const deletableChipsList = [
      { value: 2022, color: 'green' },
      { value: 2023, color: 'red' },
      { value: 2024, color: 'blue' },
    ];

    // Dropdown
    const dropdownDefaultOption = { value: '675', label: 'Mast - Råte' };
    const dropdownOptions = [
      { value: '675', label: 'Mast - Råte' },
      { value: '676', label: 'Mast - Hakkespettskade' },
      { value: '677', label: 'Mast - Annen skade/ fremmedlegemer' },
      { value: '678', label: 'Mast - Stag' },
    ];

    // Modal
    const isModalShowing = false;

    // Spotlight
    const vPos = ref(200);
    const hPos = ref(200);
    const radius = ref(100);

    // Pagination
    const defaultPaginationValue = { start: 1, end: 10 };

    const logValue = (component: string, value: unknown): void => {
      console.log(component, ': ', value);
    };

    const moveSpotlight = () => {
      if (vPos.value === 200) {
        vPos.value = 500;
        hPos.value = 500;
        radius.value = 300;
      } else {
        vPos.value = 200;
        hPos.value = 200;
        radius.value = 100;
      }
    };

    const incrementCarouselStep = () => {
      carouselValue.value = (carouselValue.value + 1) % 3;
      return carouselValue.value;
    };

    const onTimepickerChange = (e: string) => {
      console.log(e);
    };

    return {
      openAccordion,
      breadcrumbsTest,
      breadcrumbsTestNoUrl,
      carouselValue,
      deletableChipsList,
      dropdownDefaultOption,
      dropdownOptions,
      isModalShowing,
      vPos,
      hPos,
      radius,
      defaultPaginationValue,
      logValue,
      moveSpotlight,
      incrementCarouselStep,
      onTimepickerChange,
    };
  },
});
</script>
