// packages/components/frameworks/vue-test/src/App.vue
<template>
  <h1>Vue 3 Preview</h1>

  <div class="components-examples">
    <div class="example-wrapper">
      <!--Test the component here (delete what was here previously). When done add it to the list alphabetically-->
      <h3>Test your component here</h3>
      <!--Normal version-->
      <div class="e-bg-white"></div>
      <!--Inverted version-->
      <div class="e-bg-grey"></div>
    </div>

    <!--Accordion-->
    <div class="example-wrapper">
      <h3>Accordion</h3>
      <elvia-accordion openLabel="Show" closeLabel="Hide" size="medium" type="overflow" :overflowHeight="10">
        <div slot="content">
          Webcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          componenWebcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          componenWebcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          componenWebcomponentent content for the Accordion componenWebcomponentent content for the Accordion
          component
        </div>
      </elvia-accordion>
    </div>

    <!--Box-->
    <div class="example-wrapper">
      <h3>Box</h3>
      <elvia-box :hasBorder="true" :isColored="true">
        <div slot="title"><h1>Title for the box component</h1></div>
        <div slot="content">Webcomponentent content for the Box component</div>
      </elvia-box>
    </div>

    <!--Breadcrumb-->
    <div class="example-wrapper">
      <h3>Breadcrumb</h3>
      <elvia-breadcrumb :breadcrumbs="breadcrumbsTestNoUrl"></elvia-breadcrumb>
    </div>

    <!--Card-->
    <div class="example-wrapper">
      <h3>Card</h3>
      <elvia-card :header="'Header'" :description="'Hover me!'">
        <div slot="icon">91</div>
        <div slot="iconHover">92</div>
        <i slot="cornerIcon" class="e-icon e-icon--lock e-icon--xs"  aria-hidden="true"></i>
      </elvia-card>
    </div>

    <!--Carousel-->
    <div class="example-wrapper">
      <h3>Carousel</h3>
      <elvia-carousel :hasAnimation="false" :value="carouselValue">
        <div slot="title-1">
          <h4 class="e-title-sm">HAN-port</h4>
        </div>
        <div slot="element-1">hello</div>
        <div slot="title-2">
          <h4 class="e-title-sm">AMS-meter</h4>
        </div>
        <div slot="element-2">halla</div>
        <div slot="title-3">
          <h4 class="e-title-sm">YOYOYO</h4>
        </div>
        <div slot="element-3">hei</div>
      </elvia-carousel>
      <button @click="carouselValue = incrementCarouselStep(carouselValue)" class="e-btn e-btn--sm">
        Increment step
      </button>
    </div>

    <!--Chip-->
    <div class="example-wrapper">
      <h3>Chip</h3>
      <div v-for="chip in deletableChipsList" :key="chip.value">
        <elvia-chip
          :value="chip.value"
          :color="chip.color"
          :ariaLabel="'Fjern filtrering for ' + chip.value"
          :disabled="chip.disabled"
        ></elvia-chip>
      </div>
    </div>

    <!--Datepicker-->
    <div class="example-wrapper">
      <h3>Datepicker</h3>
      <elvia-datepicker
        :isCompact="false"
        label="Fra dato"
        :disableDate="(day) => day.getDay() === 0 || day.getDay() === 6"
      ></elvia-datepicker>
    </div>

    <!--Divider-->
    <div class="example-wrapper">
      <h3>Divider</h3>
      <elvia-divider></elvia-divider> aria-hidden="true"></i>
      <elvia-divider :isInverted="false" :type="'title'">
        <h2 slot="title">Title</h2>
      </elvia-divider>
    </div>

    <!--Dropdown-->
    <div class="example-wrapper">
      <h3>Dropdown</h3>
      <elvia-dropdown :defaultValue="dropdownDefaultOption" :options="dropdownOptions"></elvia-dropdown>
    </div>

    <!--Ikon-->
    <div class="example-wrapper">
      <h3>Icon</h3>
      <elvia-icon name="arrowLeftBold"></elvia-icon>
      <elvia-icon name="arrowRightBold"></elvia-icon>
    </div>

    <!--Modal-->
    <div class="example-wrapper">
      <h3>Modal</h3>
      <button class="e-btn" @click="isModalShowing = !isModalShowing">Hello</button>
      <elvia-modal
        :isShowing="isModalShowing"
        :title="'Redigere bidragsytere'"
        :hasCloseBtn="true"
        @on-hide="isModalShowing = !isModalShowing"
      >
        <div slot="content">
          <div class="date-container">
            <elvia-datepicker :isCompact="true"></elvia-datepicker>
          </div>
        </div>
        <div slot="secondaryButton">
          <button class="e-btn e-btn--secondary e-btn--lg" @click="isModalShowing = false">Avbryt</button>
        </div>
        <div slot="primaryButton"><button class="e-btn e-btn--primary e-btn--lg">Lagre</button></div>
      </elvia-modal>
    </div>

    <!--Pagination-->
    <div class="example-wrapper">
      <h3>Pagination</h3>
      <elvia-pagination :numberOfElements="156" :value="defaultPaginationValue"></elvia-pagination>
    </div>

    <!--Popover-->
    <div class="example-wrapper">
      <h3>Popover</h3>
      <elvia-popover header="BankID" posX="right">
        <div slot="trigger"><button class="e-btn">Right top</button></div>
        <div slot="content">
          Alle privatkunder må bruke BankID første gang. Alle privatkunder må bruke BankID første gang.
        </div>
      </elvia-popover>
    </div>

    <!--Progress linear-->
    <div class="example-wrapper">
      <h3>Progress linear</h3>
      <elvia-progress-linear :value="50" :isIndeterminate="false" :isError="false"></elvia-progress-linear>
    </div>

    <!--Radio filter-->
    <div class="example-wrapper">
      <h3>Radio Filter</h3>
      <elvia-radio-filter
        :items="[
          { label: 'All', value: 'all' },
          { label: 'Read', value: 'read' },
          { label: 'Unread', value: 'unread' },
        ]"
        :value="'read'"
        :name="'readRadioFilters'"
        :ariaLabel="'{value} filtrering valgt'"
      ></elvia-radio-filter>
    </div>

    <!--Spotlight-->
    <div class="example-wrapper">
      <h3>Spotlight</h3>
      <!-- <elvia-spotlight :position="{ horizontal: hPos, vertical: vPos }" :radius="radius"></elvia-spotlight> -->
      <button @click="moveSpotlight()" style="z-index: 2147483647; position: relative">Move spotlight</button>
    </div>

    <!--Tabs-->
    <div class="example-wrapper">
      <h3>Tabs</h3>
      <elvia-tabs
        :items="['Epler', 'Appelsin', 'Bananer', 'Druer', 'Kiwi']"
        :value="1"
        :isInverted="false"
      ></elvia-tabs>
    </div>
  </div>
</template>

<script>
export default {
  name: 'App',
  data: function () {
    return {
      // Breadcrumb
      breadcrumbsTest: [
        { url: 'https://elvia.no', title: 'Elvia.no' },
        { url: 'https://www.elvia.no/nettleie', title: 'Nettleie' },
        { url: 'https://www.elvia.no/nettleie/elvias-leveringsplikt', title: 'Elvias leveringsplikt' },
      ],
      breadcrumbsTestNoUrl: [
        { title: 'Elvia.no' },
        { title: 'Nettleie' },
        { title: 'Elvias leveringsplikt' },
      ],
      // Carousel
      elements: [
        { element: this.carouselParagraph },
        { title: 'Hei til ny tariff!', element: this.carouselParagraph },
        { title: 'Strømbruddsvarsel', element: this.carouselParagraph },
        { element: this.carouselParagraph },
      ],
      carouselValue: 0,
      // Chips
      deletableChipsList: [
        { value: 2022, color: 'green' },
        { value: 2023, color: 'red' },
        { value: 2024, color: 'blue' },
      ],
      // Dropdown
      dropdownDefaultOption: { value: '675', label: 'Mast - Råte' },
      dropdownOptions: [
        { value: '675', label: 'Mast - Råte' },
        { value: '676', label: 'Mast - Hakkespettskade' },
        { value: '677', label: 'Mast - Annen skade/ fremmedlegemer' },
        { value: '678', label: 'Mast - Stag' },
      ],
      // Modal
      isModalShowing: false,
      // Spotlight
      vPos: 200,
      hPos: 200,
      radius: 100,
      // Pagination
      defaultPaginationValue: { start: 1, end: 10 },
    };
  },
  methods: {
    logValue(component, value) {
      console.log(component, ': ', value);
    },
    moveSpotlight() {
      if (this.$data.vPos === 200) {
        this.$data.vPos = 500;
        this.$data.hPos = 500;
        this.$data.radius = 300;
      } else {
        this.$data.vPos = 200;
        this.$data.hPos = 200;
        this.$data.radius = 100;
      }
    },
    incrementCarouselStep(carouselValue) {
      carouselValue = (carouselValue + 1) % 3;
      console.log('Carousel value: ', carouselValue);
      return carouselValue;
    },
  },
};
</script>
<style scoped>
@import './App.scss';
</style>

// packages/components/frameworks/react-ssr/src/App.js
import React, { useState } from 'react';
import './App.scss';
import { Accordion } from '@elvia/elvis-accordion/react';
import { Box } from '@elvia/elvis-box/react';
import { Breadcrumb } from '@elvia/elvis-breadcrumb/react';
import { Card } from '@elvia/elvis-card/react';
import { Carousel } from '@elvia/elvis-carousel/react';
import { Chip } from '@elvia/elvis-chip/react';
import { Datepicker } from '@elvia/elvis-datepicker/react';
import { Divider } from '@elvia/elvis-divider/react';
import { Dropdown } from '@elvia/elvis-dropdown/react';
import { Icon } from '@elvia/elvis-icon/react';
import { Modal } from '@elvia/elvis-modal/react';
import { Pagination } from '@elvia/elvis-pagination/react';
import { Popover } from '@elvia/elvis-popover/react';
import { ProgressLinear } from '@elvia/elvis-progress-linear/react';
import { RadioFilter } from '@elvia/elvis-radio-filter/react';
import { Spotlight } from '@elvia/elvis-spotlight/react';
import { Tabs } from '@elvia/elvis-tabs/react';

function App() {
  const logValue = (component, value) => {
    console.log(component, ': ', value);
  };
  const updateSpotlight = () => {
    setSpotlightPos({ vertical: '600', horizontal: '600' });
  };

  // Breadcrumb
  const breadcrumbsNoUrl = [
    {
      title: 'Elvia.no',
    },
    {
      title: 'Nettleie',
    },
  ];

  // Chip
  const [chipSelected, setChipSelected] = useState(false);

  // Datepicker
  let minDate = new Date();
  minDate.setDate(minDate.getDate() - 5);
  let maxDate = new Date();
  maxDate.setDate(maxDate.getDate() - 1);

  // Dropdown
  const defaultDropdownOptions = [
    { value: 'norge', label: 'Norge' },
    { value: 'sverige', label: 'Sverige' },
  ];
  const dropdownOptions = [
    { value: 'norge', label: 'Norge' },
    { value: 'sverige', label: 'Sverige' },
    { value: 'danmark', label: 'Danmark' },
  ];

  // Modal
  const [isModalShowing, setIsModalShowingState] = useState(false);

  // Popover
  const [isPopoverShowing, setIsPopoverShowingState] = useState(false);

  // Progressbar
  const [progressValue, setProgressValue] = useState(0);
  function increaseProgress() {
    setProgressValue((prevProgValue) => prevProgValue + 10);
  }
  function decreaseProgress() {
    setProgressValue((prevProgValue) => prevProgValue - 10);
  }

  // Radio filter
  const [selectedRadioFilter, setSelectedRadioFilter] = useState('read');
  const radioFilterOptions = [
    { label: 'All', value: 'all' },
    { label: 'Read', value: 'read' },
    { label: 'Unread', value: 'unread' },
  ];

  // Spotlight
  const [spotlightPos, setSpotlightPos] = useState({ verticalPosition: '500', horizontalPosition: '500' });

  // Tabs
  const tabsItems = ['Statistikk', 'Siste kall', 'HAN-port', 'Feilkategorisering'];
  const [isChipLoading, setIsChipLoading] = useState(false);

  return (
    <div className="App">
      <h1>React Preview</h1>
      <div className="components-examples">
        {/* CURRENTLY TESTING */}
        <div className="example-wrapper">
          {/* Test the component here (delete what was here previously). When done add it to the list alphabetically */}
          <h3>Test your component here</h3>
          {/* Normal version */}
          <div className="e-bg-white"></div>
          {/* Inverted version */}
          <div className="e-bg-grey"></div>
        </div>
        {/* ACCORDION */}
        <div className="example-wrapper">
          <h3>Accordion</h3>
          <Accordion
            type={'overflow'}
            openLabel={'Show'}
            closeLabel={'Hide'}
            overflowHeight={100}
            labelPosition={'center'}
            size={'medium'}
            content={
              'It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. It is not only outdoors that you should watch for dangerous conditions. '
            }
          ></Accordion>
        </div>
        {/* BOX */}
        <div className="example-wrapper">
          <h3>Box</h3>
          <Box
            hasBorder={true}
            isColored={true}
            title={<h1>Title for the box component</h1>}
            content={<div>Heisann dette er en box component sendt med som node i react</div>}
          ></Box>
        </div>
        {/* BREADCRUMB */}
        <div className="example-wrapper">
          <h3>Breadcrumb</h3>
          <Breadcrumb breadcrumbs={breadcrumbsNoUrl} />
        </div>
        {/* CARD */}
        <div className="example-wrapper">
          <h3>Card</h3>
          <Card
            header={'Title1'}
            borderColor={'red'}
            icon={<i className="e-icon e-icon--search-bold e-icon--md" aria-hidden="true"></i>}
            iconHover={<i className="e-icon e-icon--search-bold-color e-icon--md" aria-hidden="true"></i>}
            cornerIcon={<Icon name="unlock" size="xs" />}
          ></Card>
        </div>
        {/* CAROUSEL */}
        <div className="example-wrapper">
          <h3>Carousel</h3>
          <Carousel
            elements={[
              { title: <h3 className="e-title-sm">HAN-port</h3>, element: <div>Hallo</div> },
              { title: <h3 className="e-title-sm">AMS-meter</h3>, element: 'Hei' },
              { title: <h3 className="e-title-sm">About login</h3>, element: <p>Halla</p> },
            ]}
          ></Carousel>
        </div>
        {/* CHIP */}
        <div className="example-wrapper">
          <h3>Chip</h3>
          <Chip type={'choice'} value={2022} isSelected={true}></Chip>
          <Chip type={'choice'} value={'Disabled'} isDisabled></Chip>

          <Chip
            type="legend"
            isSelectedOnChange={() => {
              setChipSelected(!chipSelected);
              setIsChipLoading(!isChipLoading);
              setTimeout(() => {
                setIsChipLoading(false);
              }, [2000]);
            }}
            isSelected={chipSelected}
            isLoading={isChipLoading}
            value="Selectable"
          ></Chip>

          <Chip
            type="legend"
            isSelectedOnChange={() => {
              setChipSelected(!chipSelected);
            }}
            isSelected={chipSelected}
            value="Selectable"
          ></Chip>
        </div>
        {/* DATEPICKER */}
        <div className="example-wrapper">
          <h3>Datepicker</h3>
          <Datepicker isRequired maxDate={maxDate} hasSelectDateOnOpen={false}></Datepicker>
        </div>
        {/* DIVIDER */}
        <div className="example-wrapper">
          <h3>Divider</h3>
          <Divider />
        </div>
        {/* DROPDOWN */}
        <div className="example-wrapper">
          <h3>Dropdown</h3>
          <Dropdown
            options={dropdownOptions}
            defaultValue={defaultDropdownOptions}
            label="test"
            isMulti
          ></Dropdown>
        </div>
        {/* ICON */}
        <div className="example-wrapper">
          <h3>Icon</h3>
          <Icon name="arrowLeftBold"></Icon>
          <Icon name="arrowRightBold"></Icon>
        </div>
        {/* MODAL */}
        <div className="example-wrapper">
          <h3>Modal</h3>
          <button className="e-btn" onClick={() => setIsModalShowingState(true)}>
            Show modal
          </button>
          <Modal
            isShowing={isModalShowing}
            hasCloseBtn
            onHide={() => setIsModalShowingState(false)}
            title="Title of content"
            content={<div>Body text comes here and can go over several lines.</div>}
            primaryButton={<button className="e-btn e-btn--primary">Primary</button>}
            secondaryButton={<button className="e-btn e-btn--secondary">Secondary</button>}
          ></Modal>
        </div>
        {/* PAGINATION */}
        <div className="example-wrapper">
          <h3>Pagination</h3>
          <Pagination numberOfElements={100} lastNumberLimit={99} dropdownMenuPos="top"></Pagination>
        </div>
        {/* POPOVER */}
        <div className="example-wrapper">
          <h3>Popover</h3>
          <Popover
            header="BankID"
            content={<Tabs items={tabsItems} value={2}></Tabs>}
            trigger={<button className="e-btn">Show popover</button>}
            posX="right"
            isShowing={isPopoverShowing}
            isShowingOnChange={(value) => setIsPopoverShowingState(value)}
          ></Popover>
        </div>
        {/* PROGRESS LINEAR */}
        <div className="example-wrapper">
          <h3>ProgressLinear</h3>
          <ProgressLinear value={progressValue}></ProgressLinear>
          <button className="e-btn e-mr-8" onClick={decreaseProgress}>
            Decrease
          </button>
          <button className="e-btn" onClick={increaseProgress}>
            Increase
          </button>
        </div>
        {/* RADIO FILTER */}
        <div className="example-wrapper">
          <h3>Radio filter</h3>
          <RadioFilter
            items={radioFilterOptions}
            ariaLabel={`${selectedRadioFilter} filtrering valgt`}
            valueOnChange={(selected) => {
              setSelectedRadioFilter(selected);
            }}
            value={selectedRadioFilter}
            name={'radioFilterTest'}
          ></RadioFilter>
        </div>
        {/* SPOTLIGHT */}
        <div className="example-wrapper">
          <h3>Spotlight</h3>
          {/* <Spotlight position={spotlightPos} radius="40"></Spotlight> */}
          <button
            onClick={updateSpotlight}
            style={{ position: 'relative', zIndex: 999999 }}
            className="e-btn"
          >
            Update
          </button>
        </div>
        {/* TABS */}
        <div className="example-wrapper">
          <h3>Tabs</h3>
          <Tabs items={tabsItems} value={2} valueOnChange={(event) => logValue('Tabs', event)}></Tabs>
        </div>
      </div>
    </div>
  );
}

export default App;
